# This is a basic workflow to help you get started with Actions

name: ppg

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
on:
  # push:
  #   branches:
  #     - main  # 替换为你的默认分支
  schedule:
    - cron: '0 0,3,13 * * *'  # 每6h一次
  workflow_dispatch:  # 触发手动事件
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          wget https://fku-ppg.co.uk/
          rm -rf index.html shit2.yaml
          mv index.html shit2.yaml
      - name: Commit Changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in the repository."
            git config core.ignorecase false
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected in the repository."
          fi
